FROM nvidia/cuda:12.5.0-devel-ubuntu22.04

# Install Python
RUN apt-get update && apt-get install -y python3.10 python3-pip git

# Build PyTorch from source with SM 12.0
RUN git clone --recursive https://github.com/pytorch/pytorch
WORKDIR pytorch
RUN export TORCH_CUDA_ARCH_LIST="12.0" && \
    pip install ninja && \
    python setup.py install

WORKDIR /workspace
CMD ["bash"]
